import { spawn } from 'child_process';
import crypto from 'crypto';
import fs from 'fs-extra';
import os from 'os';
import path from 'path';
import { EXECUTION_LIMITS, REQUEST_LIMITS } from '../config/constants.js';

const TMP_DIR = path.resolve(os.tmpdir());
const SAFE_BINARY_NAME = /^code_[A-Za-z0-9_-]+\.out$/;

const sessions = new Map();

function isSafeBinaryPath(binaryPath) {
  if (typeof binaryPath !== 'string' || !binaryPath.trim()) {
    return false;
  }

  const resolved = path.resolve(binaryPath);
  const inTmpDir = resolved.startsWith(`${TMP_DIR}${path.sep}`);
  const safeName = SAFE_BINARY_NAME.test(path.basename(resolved));

  return inTmpDir && safeName;
}

function normalizeArgs(args) {
  if (!Array.isArray(args)) {
    return [];
  }

  return args
    .slice(0, REQUEST_LIMITS.args)
    .map((arg) => (typeof arg === 'string' ? arg : String(arg)));
}

function ensureCapacity() {
  if (sessions.size < EXECUTION_LIMITS.maxSessions) {
    return;
  }

  for (const [sessionId, session] of sessions) {
    if (session.done) {
      sessions.delete(sessionId);
      return;
    }
  }

  throw new Error('Too many active run sessions. Please wait and try again.');
}

async function finalizeSession(session, options = {}) {
  const { forceKill = false } = options;

  if (forceKill && session.child && !session.done) {
    session.child.kill('SIGKILL');
  }

  if (session.cleanupTimer) {
    clearTimeout(session.cleanupTimer);
    session.cleanupTimer = null;
  }

  const binaryPath = session.binaryPath;
  if (binaryPath) {
    await fs.remove(binaryPath).catch(() => {});
  }
}

function scheduleSessionCleanup(sessionId) {
  const session = sessions.get(sessionId);
  if (!session) return;

  if (session.cleanupTimer) {
    clearTimeout(session.cleanupTimer);
  }

  session.cleanupTimer = setTimeout(async () => {
    const stale = sessions.get(sessionId);
    if (!stale || !stale.done) {
      return;
    }

    await finalizeSession(stale).catch(() => {});
    sessions.delete(sessionId);
  }, EXECUTION_LIMITS.sessionRetentionMs);
  session.cleanupTimer.unref?.();
}

export async function startRunSession(binaryPath, args = []) {
  const resolvedBinaryPath = path.resolve(binaryPath || '');
  const safeBinaryPath = isSafeBinaryPath(resolvedBinaryPath) ? resolvedBinaryPath : null;

  if (!safeBinaryPath) {
    return {
      success: false,
      error: 'Invalid binary path. Only temporary binaries generated by this service can be executed.'
    };
  }

  const exists = await fs.pathExists(safeBinaryPath);
  if (!exists) {
    return {
      success: false,
      error: `Binary not found: ${safeBinaryPath}`
    };
  }

  ensureCapacity();

  const sessionId = crypto.randomUUID();
  const normalizedArgs = normalizeArgs(args);
  const child = spawn(safeBinaryPath, normalizedArgs, { stdio: 'pipe' });

  const session = {
    sessionId,
    binaryPath: safeBinaryPath,
    child,
    stdout: '',
    stderr: '',
    outputBytes: 0,
    done: false,
    exitCode: null,
    executionTime: 0,
    startTime: Date.now(),
    timedOut: false,
    outputLimitHit: false,
    cleanupTimer: null
  };

  const timeoutTimer = setTimeout(() => {
    session.timedOut = true;
    child.kill('SIGKILL');
  }, EXECUTION_LIMITS.timeoutMs);

  child.stdout.on('data', (chunk) => {
    const text = chunk.toString();
    session.outputBytes += chunk.length;
    session.stdout += text;

    if (!session.outputLimitHit && session.outputBytes > EXECUTION_LIMITS.outputBytes) {
      session.outputLimitHit = true;
      child.kill('SIGKILL');
    }
  });

  child.stderr.on('data', (chunk) => {
    const text = chunk.toString();
    session.outputBytes += chunk.length;
    session.stderr += text;

    if (!session.outputLimitHit && session.outputBytes > EXECUTION_LIMITS.outputBytes) {
      session.outputLimitHit = true;
      child.kill('SIGKILL');
    }
  });

  child.on('error', (err) => {
    session.done = true;
    session.executionTime = Date.now() - session.startTime;
    session.exitCode = 1;
    session.stderr = `${session.stderr}${session.stderr ? '\n' : ''}${err.message}`;
    clearTimeout(timeoutTimer);
    void finalizeSession(session).catch(() => {});
    scheduleSessionCleanup(sessionId);
  });

  child.on('close', async (code) => {
    session.done = true;
    session.executionTime = Date.now() - session.startTime;
    session.exitCode = code ?? (session.timedOut ? 124 : session.outputLimitHit ? 122 : 1);

    if (session.timedOut && !session.stderr) {
      session.stderr = `Execution timed out after ${EXECUTION_LIMITS.timeoutMs}ms`;
    }

    if (session.outputLimitHit && !session.stderr) {
      session.stderr = `Execution output exceeded ${EXECUTION_LIMITS.outputBytes} bytes`;
    }

    clearTimeout(timeoutTimer);
    await finalizeSession(session).catch(() => {});
    scheduleSessionCleanup(sessionId);
  });

  sessions.set(sessionId, session);

  return { success: true, sessionId };
}

export function pollRunSession(sessionId) {
  const session = sessions.get(sessionId);
  if (!session) {
    return {
      found: false,
      error: 'Run session not found'
    };
  }

  return {
    found: true,
    sessionId,
    stdout: session.stdout,
    stderr: session.stderr,
    done: session.done,
    exitCode: session.exitCode,
    executionTime: session.executionTime
  };
}

export function sendRunInput(sessionId, input) {
  const session = sessions.get(sessionId);
  if (!session) {
    return { success: false, error: 'Run session not found' };
  }

  if (session.done) {
    return { success: false, error: 'Run session has already completed' };
  }

  if (typeof input !== 'string') {
    return { success: false, error: 'Input must be a string' };
  }

  if (Buffer.byteLength(input, 'utf8') > REQUEST_LIMITS.runInputBytes) {
    return {
      success: false,
      error: `Input exceeds maximum allowed size of ${REQUEST_LIMITS.runInputBytes} bytes`
    };
  }

  session.child.stdin.write(input);
  return { success: true };
}

export function stopRunSession(sessionId) {
  const session = sessions.get(sessionId);
  if (!session) {
    return { success: false, error: 'Run session not found' };
  }

  if (!session.done) {
    session.child.kill('SIGKILL');
  }

  return { success: true };
}
