import { spawn } from 'child_process';
import crypto from 'crypto';
import fs from 'fs-extra';
import os from 'os';
import path from 'path';
import { EXECUTION_LIMITS, REQUEST_LIMITS } from '../config/constants.js';

const TMP_DIR = path.resolve(os.tmpdir());
const SAFE_BINARY_NAME = /^code_[A-Za-z0-9_-]+\.out$/;
const STDBUF_BINARIES = ['/usr/bin/stdbuf', '/bin/stdbuf'];
const STDBUF_PATH = STDBUF_BINARIES.find((candidate) => fs.pathExistsSync(candidate)) ?? null;
const SCRIPT_BINARIES = ['/usr/bin/script', '/bin/script'];
const SCRIPT_PATH = SCRIPT_BINARIES.find((candidate) => fs.pathExistsSync(candidate)) ?? null;

const sessions = new Map();

function shellQuote(arg) {
  const escaped = String(arg).replace(/'/g, "'\"'\"'");
  return `'${escaped}'`;
}

function spawnRunProcess(binaryPath, normalizedArgs) {
  if (SCRIPT_PATH) {
    const command = [binaryPath, ...normalizedArgs].map(shellQuote).join(' ');
    const child = spawn(SCRIPT_PATH, ['-qfec', command, '/dev/null'], { stdio: 'pipe' });
    return { child, usesPty: true };
  }

  if (STDBUF_PATH) {
    const child = spawn(STDBUF_PATH, ['-o0', '-e0', binaryPath, ...normalizedArgs], { stdio: 'pipe' });
    return { child, usesPty: false };
  }

  const child = spawn(binaryPath, normalizedArgs, { stdio: 'pipe' });
  return { child, usesPty: false };
}

function isSafeBinaryPath(binaryPath) {
  if (typeof binaryPath !== 'string' || !binaryPath.trim()) {
    return false;
  }

  const resolved = path.resolve(binaryPath);
  const inTmpDir = resolved.startsWith(`${TMP_DIR}${path.sep}`);
  const safeName = SAFE_BINARY_NAME.test(path.basename(resolved));

  return inTmpDir && safeName;
}

function normalizeArgs(args) {
  if (!Array.isArray(args)) {
    return [];
  }

  return args
    .slice(0, REQUEST_LIMITS.args)
    .map((arg) => (typeof arg === 'string' ? arg : String(arg)));
}

function ensureCapacity() {
  if (sessions.size < EXECUTION_LIMITS.maxSessions) {
    return;
  }

  for (const [sessionId, session] of sessions) {
    if (session.done) {
      sessions.delete(sessionId);
      return;
    }
  }

  throw new Error('Too many active run sessions. Please wait and try again.');
}

async function finalizeSession(session, options = {}) {
  const { forceKill = false } = options;

  if (forceKill && session.child && !session.done) {
    session.child.kill('SIGKILL');
  }

  if (session.cleanupTimer) {
    clearTimeout(session.cleanupTimer);
    session.cleanupTimer = null;
  }

  const binaryPath = session.binaryPath;
  if (binaryPath) {
    await fs.remove(binaryPath).catch(() => {});
  }
}

function scheduleSessionCleanup(sessionId) {
  const session = sessions.get(sessionId);
  if (!session) return;

  if (session.cleanupTimer) {
    clearTimeout(session.cleanupTimer);
  }

  session.cleanupTimer = setTimeout(async () => {
    const stale = sessions.get(sessionId);
    if (!stale || !stale.done) {
      return;
    }

    await finalizeSession(stale).catch(() => {});
    sessions.delete(sessionId);
  }, EXECUTION_LIMITS.sessionRetentionMs);
  session.cleanupTimer.unref?.();
}

export async function startRunSession(binaryPath, args = []) {
  const resolvedBinaryPath = path.resolve(binaryPath || '');
  const safeBinaryPath = isSafeBinaryPath(resolvedBinaryPath) ? resolvedBinaryPath : null;

  if (!safeBinaryPath) {
    return {
      success: false,
      error: 'Invalid binary path. Only temporary binaries generated by this service can be executed.'
    };
  }

  const exists = await fs.pathExists(safeBinaryPath);
  if (!exists) {
    return {
      success: false,
      error: `Binary not found: ${safeBinaryPath}`
    };
  }

  ensureCapacity();

  const sessionId = crypto.randomUUID();
  const normalizedArgs = normalizeArgs(args);
  const { child, usesPty } = spawnRunProcess(safeBinaryPath, normalizedArgs);

  const session = {
    sessionId,
    binaryPath: safeBinaryPath,
    child,
    output: '',
    stdout: '',
    stderr: '',
    outputBytes: 0,
    done: false,
    exitCode: null,
    executionTime: 0,
    startTime: Date.now(),
    timedOut: false,
    outputLimitHit: false,
    inputClosed: false,
    usesPty,
    cleanupTimer: null,
    timeoutTimer: null,
    refreshTimeout: null
  };

  const refreshTimeout = () => {
    if (session.timeoutTimer) {
      clearTimeout(session.timeoutTimer);
    }
    session.timeoutTimer = setTimeout(() => {
      session.timedOut = true;
      child.kill('SIGKILL');
    }, EXECUTION_LIMITS.timeoutMs);
    session.timeoutTimer.unref?.();
  };
  session.refreshTimeout = refreshTimeout;
  refreshTimeout();

  child.stdout.on('data', (chunk) => {
    const text = chunk.toString().replace(/\r\n/g, '\n');
    session.outputBytes += chunk.length;
    session.output += text;
    session.stdout += text;
    refreshTimeout();

    if (!session.outputLimitHit && session.outputBytes > EXECUTION_LIMITS.outputBytes) {
      session.outputLimitHit = true;
      child.kill('SIGKILL');
    }
  });

  child.stderr.on('data', (chunk) => {
    const text = chunk.toString().replace(/\r\n/g, '\n');
    session.outputBytes += chunk.length;
    session.output += text;
    session.stderr += text;
    refreshTimeout();

    if (!session.outputLimitHit && session.outputBytes > EXECUTION_LIMITS.outputBytes) {
      session.outputLimitHit = true;
      child.kill('SIGKILL');
    }
  });

  child.on('error', (err) => {
    session.done = true;
    session.executionTime = Date.now() - session.startTime;
    session.exitCode = 1;
    session.stderr = `${session.stderr}${session.stderr ? '\n' : ''}${err.message}`;
    if (session.timeoutTimer) {
      clearTimeout(session.timeoutTimer);
      session.timeoutTimer = null;
    }
    void finalizeSession(session).catch(() => {});
    scheduleSessionCleanup(sessionId);
  });

  child.on('close', async (code) => {
    session.done = true;
    session.executionTime = Date.now() - session.startTime;
    session.exitCode = code ?? (session.timedOut ? 124 : session.outputLimitHit ? 122 : 1);

    if (session.timedOut && !session.stderr) {
      session.stderr = `Execution timed out after ${EXECUTION_LIMITS.timeoutMs}ms`;
    }

    if (session.outputLimitHit && !session.stderr) {
      session.stderr = `Execution output exceeded ${EXECUTION_LIMITS.outputBytes} bytes`;
    }

    if (session.timeoutTimer) {
      clearTimeout(session.timeoutTimer);
      session.timeoutTimer = null;
    }
    await finalizeSession(session).catch(() => {});
    scheduleSessionCleanup(sessionId);
  });

  sessions.set(sessionId, session);

  return { success: true, sessionId };
}

export function pollRunSession(sessionId) {
  const session = sessions.get(sessionId);
  if (!session) {
    return {
      found: false,
      error: 'Run session not found'
    };
  }

  return {
    found: true,
    sessionId,
    output: session.output,
    stdout: session.stdout,
    stderr: session.stderr,
    done: session.done,
    exitCode: session.exitCode,
    executionTime: session.executionTime
  };
}

export function sendRunInput(sessionId, input) {
  const session = sessions.get(sessionId);
  if (!session) {
    return { success: false, error: 'Run session not found' };
  }

  if (session.done) {
    return { success: false, error: 'Run session has already completed' };
  }

  if (typeof input !== 'string') {
    return { success: false, error: 'Input must be a string' };
  }

  if (session.inputClosed) {
    return { success: false, error: 'stdin is already closed for this run session' };
  }

  if (Buffer.byteLength(input, 'utf8') > REQUEST_LIMITS.runInputBytes) {
    return {
      success: false,
      error: `Input exceeds maximum allowed size of ${REQUEST_LIMITS.runInputBytes} bytes`
    };
  }

  try {
    session.child.stdin.write(input);
    if (!session.usesPty) {
      session.output += input;
    }
    session.refreshTimeout?.();
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Failed to write to program stdin'
    };
  }
  return { success: true };
}

export function closeRunInput(sessionId) {
  const session = sessions.get(sessionId);
  if (!session) {
    return { success: false, error: 'Run session not found' };
  }

  if (session.done) {
    return { success: false, error: 'Run session has already completed' };
  }

  if (session.inputClosed) {
    return { success: true };
  }

  try {
    session.child.stdin.end();
    session.inputClosed = true;
    session.output += '^D\n';
    session.refreshTimeout?.();
    return { success: true };
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Failed to close program stdin'
    };
  }
}

export function stopRunSession(sessionId) {
  const session = sessions.get(sessionId);
  if (!session) {
    return { success: false, error: 'Run session not found' };
  }

  if (!session.done) {
    session.child.kill('SIGKILL');
  }

  return { success: true };
}
